import os

TWITTER_API_KEY = os.environ.get("TWITTER_API_KEY") or ""
TWITTER_API_SECRET = os.environ.get("TWITTER_API_SECRET") or ""
TWITTER_ACCESS_TOKEN_KEY = os.environ.get("TWITTER_ACCESS_TOKEN_KEY") or ""
TWITTER_ACCESS_TOKEN_SECRET = os.environ.get("TWITTER_ACCESS_TOKEN_SECRET") or ""

GITHUB_ACCESS_KEY = os.environ.get("GIT_ACCESS_KEY") or ""
GITHUB_ID = "310o"
GITHUB_REPO_URL = "GoBeromsu/solvedAcBot"
GITHUB_ISSUE_ID = 1
TWEET_LENGTH_LIMIT = 140
